AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/EachWithObject:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/SignalException:
  EnforcedStyle: semantic

Style/PredicateName:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8
